# Generated by Codex on 2026-05-08

import uuid
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def create_consultations_for_existing_bookings(apps, schema_editor):
    Booking = apps.get_model("appointments", "Booking")
    Consultation = apps.get_model("consultations", "Consultation")
    for booking in Booking.objects.all().only("id"):
        Consultation.objects.get_or_create(
            booking_id=booking.id,
            defaults={"room_id": f"consultation_{booking.id.hex}"},
        )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("appointments", "0005_booking_consultation_fee_booking_gst_amount_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Consultation",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("room_id", models.CharField(max_length=255, unique=True)),
                ("status", models.CharField(choices=[("SCHEDULED", "Scheduled"), ("WAITING", "Waiting"), ("ONGOING", "Ongoing"), ("COMPLETED", "Completed"), ("CANCELLED", "Cancelled")], default="SCHEDULED", max_length=20)),
                ("psychologist_joined", models.BooleanField(default=False)),
                ("patient_joined", models.BooleanField(default=False)),
                ("patient_requested_join", models.BooleanField(default=False)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("zego_recording_task_id", models.CharField(blank=True, max_length=80)),
                ("recording_status", models.CharField(choices=[("NOT_STARTED", "Not Started"), ("STARTING", "Starting"), ("RECORDING", "Recording"), ("STOPPING", "Stopping"), ("UPLOADED", "Uploaded"), ("FAILED", "Failed")], default="NOT_STARTED", max_length=20)),
                ("recording_file_url", models.URLField(blank=True, max_length=1000)),
                ("recording_metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("booking", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="consultation_session", to="appointments.booking")),
            ],
        ),
        migrations.CreateModel(
            name="ConsultationMessage",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("text", models.TextField()),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                ("consultation", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="messages", to="consultations.consultation")),
                ("sender", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="consultation_messages", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["sent_at"],
            },
        ),
        migrations.AddIndex(
            model_name="consultation",
            index=models.Index(fields=["status", "started_at"], name="consultatio_status_b5eb01_idx"),
        ),
        migrations.AddIndex(
            model_name="consultation",
            index=models.Index(fields=["recording_status"], name="consultatio_recordi_b7b045_idx"),
        ),
        migrations.AddIndex(
            model_name="consultationmessage",
            index=models.Index(fields=["consultation", "sent_at"], name="consultatio_consult_48bb8f_idx"),
        ),
        migrations.RunPython(create_consultations_for_existing_bookings, migrations.RunPython.noop),
    ]
