# Generated by Codex on 2026-05-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consultations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="consultation",
            name="patient_note",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="consultation",
            name="psychologist_note",
            field=models.TextField(blank=True),
        ),
    ]
