# Generated by Codex on 2026-05-21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("consultations", "0002_consultation_notes"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="consultation",
            name="consultatio_recordi_b7b045_idx",
        ),
        migrations.RemoveField(
            model_name="consultation",
            name="zego_recording_task_id",
        ),
        migrations.RemoveField(
            model_name="consultation",
            name="recording_status",
        ),
        migrations.RemoveField(
            model_name="consultation",
            name="recording_file_url",
        ),
        migrations.RemoveField(
            model_name="consultation",
            name="recording_metadata",
        ),
    ]
