# Generated by Codex on 2026-05-13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("consultations", "0002_consultation_notes"),
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PatientSummary",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("summary", models.TextField(blank=True)),
                ("model", models.CharField(blank=True, max_length=120)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("READY", "Ready"),
                            ("FAILED", "Failed"),
                            ("SKIPPED", "Skipped"),
                        ],
                        default="SKIPPED",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("generated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "last_consultation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="summary_updates",
                        to="consultations.consultation",
                    ),
                ),
                (
                    "patient",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="summary_report",
                        to="patients.patientprofile",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="patientsummary",
            index=models.Index(fields=["status", "generated_at"], name="patient_sum_status_fb8416_idx"),
        ),
    ]
