# Generated by Django 5.2.11 on 2026-04-16 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='chatroom',
            new_name='chat_chatro_patient_de28f7_idx',
            old_name='chat_chatro_patient_9b3b6d_idx',
        ),
        migrations.RenameIndex(
            model_name='chatroom',
            new_name='chat_chatro_psychol_fac4e0_idx',
            old_name='chat_chatro_psychol_653d38_idx',
        ),
        migrations.RenameIndex(
            model_name='message',
            new_name='chat_messag_room_id_5feac5_idx',
            old_name='chat_messag_room_id_efb2c6_idx',
        ),
        migrations.RenameIndex(
            model_name='message',
            new_name='chat_messag_sender__b02346_idx',
            old_name='chat_messag_sender__a6d987_idx',
        ),
    ]
