# Generated by Django 5.2.11 on 2026-05-21 15:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0006_drop_moved_consultation_columns'),
        ('patients', '0001_initial'),
        ('psychologists', '0004_psychologistprofile_highest_education'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('complaint_id', models.CharField(editable=False, max_length=32, unique=True)),
                ('category', models.CharField(choices=[('PSYCHOLOGIST_BEHAVIOR', 'Psychologist behavior'), ('SESSION_ENDED_EARLY', 'Session ended early'), ('CONSULTATION_QUALITY', 'Consultation quality'), ('TECHNICAL_ISSUE', 'Technical issue'), ('PRIVACY_CONCERN', 'Privacy concern'), ('PAYMENT_ISSUE', 'Payment issue'), ('OTHER', 'Other')], max_length=40)),
                ('subject', models.CharField(max_length=180)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('PENDING_REVIEW', 'Pending Review'), ('UNDER_REVIEW', 'Under Review'), ('PSYCHOLOGIST_RESPONSE_PENDING', 'Psychologist Response Pending'), ('RESOLVED', 'Resolved'), ('REJECTED', 'Rejected')], default='PENDING_REVIEW', max_length=40)),
                ('complaint_allowed_until', models.DateTimeField()),
                ('admin_response', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='complaint', to='appointments.booking')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='patients.patientprofile')),
                ('psychologist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='psychologists.psychologistprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComplaintAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='complaints/evidence/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='complaints.complaint')),
            ],
        ),
        migrations.CreateModel(
            name='ComplaintTimelineEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('SUBMITTED', 'Complaint Submitted'), ('STATUS_CHANGED', 'Status Changed'), ('ADMIN_RESPONSE', 'Admin Response Added'), ('RESOLVED', 'Complaint Resolved'), ('REJECTED', 'Complaint Rejected')], max_length=40)),
                ('title', models.CharField(max_length=180)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='complaints.complaint')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['patient', 'status', 'created_at'], name='complaints__patient_1c90d6_idx'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['psychologist', 'status', 'created_at'], name='complaints__psychol_e13767_idx'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['complaint_id'], name='complaints__complai_ea9dba_idx'),
        ),
        migrations.AddIndex(
            model_name='complainttimelineevent',
            index=models.Index(fields=['complaint', 'created_at'], name='complaints__complai_80319b_idx'),
        ),
    ]
