# Generated by Codex on 2026-05-21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("complaints", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="complaint",
            name="admin_request_message",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="complaint",
            name="internal_admin_note",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="complaint",
            name="psychologist_response",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="complaint",
            name="psychologist_response_requested_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="complaint",
            name="psychologist_responded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="complaint",
            name="resolved_by",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="resolved_complaints", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="complaint",
            name="severity",
            field=models.CharField(choices=[("LOW", "Low"), ("MEDIUM", "Medium"), ("HIGH", "High")], default="MEDIUM", max_length=20),
        ),
        migrations.AddField(
            model_name="complaint",
            name="show_to_psychologist",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="complaint",
            name="status",
            field=models.CharField(choices=[("PENDING_REVIEW", "Pending Review"), ("UNDER_REVIEW", "Under Review"), ("PSYCHOLOGIST_RESPONSE_PENDING", "Psychologist Response Pending"), ("PSYCHOLOGIST_RESPONSE_SUBMITTED", "Psychologist Response Submitted"), ("RESOLVED", "Resolved"), ("REJECTED", "Rejected")], default="PENDING_REVIEW", max_length=40),
        ),
        migrations.AlterField(
            model_name="complainttimelineevent",
            name="event_type",
            field=models.CharField(choices=[("SUBMITTED", "Complaint Submitted"), ("STATUS_CHANGED", "Status Changed"), ("ADMIN_RESPONSE", "Admin Response Added"), ("PSYCHOLOGIST_REQUESTED", "Psychologist Response Requested"), ("PSYCHOLOGIST_RESPONDED", "Psychologist Responded"), ("RESOLVED", "Complaint Resolved"), ("REJECTED", "Complaint Rejected")], max_length=40),
        ),
        migrations.CreateModel(
            name="PsychologistComplaintAttachment",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("file", models.FileField(upload_to="complaints/psychologist-evidence/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("complaint", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="psychologist_attachments", to="complaints.complaint")),
            ],
        ),
        migrations.AddIndex(
            model_name="complaint",
            index=models.Index(fields=["show_to_psychologist", "status", "created_at"], name="complaints__show_to_2a635e_idx"),
        ),
        migrations.AddIndex(
            model_name="complaint",
            index=models.Index(fields=["severity", "created_at"], name="complaints__severit_d00d2d_idx"),
        ),
    ]
