# Generated by Django 5.2.11 on 2026-05-21 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_admin_psychologist_workflow'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='complaint',
            new_name='complaints__show_to_c54b9c_idx',
            old_name='complaints__show_to_2a635e_idx',
        ),
        migrations.RenameIndex(
            model_name='complaint',
            new_name='complaints__severit_c8139a_idx',
            old_name='complaints__severit_d00d2d_idx',
        ),
    ]
