# Generated by Django 5.2.11 on 2026-03-06 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='join_requested',
            field=models.BooleanField(default=False),
        ),
    ]
