# Generated by Codex on 2026-05-14

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("appointments", "0006_drop_moved_consultation_columns"),
        ("patients", "0001_initial"),
        ("psychologists", "0004_psychologistprofile_highest_education"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsultationReview",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("rating", models.PositiveSmallIntegerField()),
                ("review", models.TextField(blank=True)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("booking", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="review", to="appointments.booking")),
                ("patient", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="consultation_reviews", to="patients.patientprofile")),
                ("psychologist", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="consultation_reviews", to="psychologists.psychologistprofile")),
            ],
            options={
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.AddIndex(
            model_name="consultationreview",
            index=models.Index(fields=["psychologist", "patient", "submitted_at"], name="reviews_con_psycho_5b14d6_idx"),
        ),
        migrations.AddIndex(
            model_name="consultationreview",
            index=models.Index(fields=["booking"], name="reviews_con_booking_9db5a7_idx"),
        ),
    ]
