# Generated by Django 5.2.11 on 2026-05-14 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='consultationreview',
            new_name='reviews_con_psychol_64f9f6_idx',
            old_name='reviews_con_psycho_5b14d6_idx',
        ),
        migrations.RenameIndex(
            model_name='consultationreview',
            new_name='reviews_con_booking_0e41c5_idx',
            old_name='reviews_con_booking_9db5a7_idx',
        ),
    ]
