# Generated by Django 5.2.11 on 2026-05-20 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbotmessage',
            name='quick_replies',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
