# Generated by Django 5.2.11 on 2026-03-06 16:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychologists', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PsychologistProfile',
            fields=[
                ('psychologist_id', models.CharField(editable=False, max_length=12, primary_key=True, serialize=False)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='psychologists/profile_pictures/')),
                ('audio_intro', models.FileField(blank=True, null=True, upload_to='psychologists/audio_intro/')),
                ('phone_number', models.CharField(max_length=15)),
                ('about', models.TextField()),
                ('street_address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('job_title', models.CharField(max_length=255)),
                ('years_of_experience', models.PositiveIntegerField()),
                ('consultation_fee', models.DecimalField(decimal_places=2, max_digits=8)),
                ('certificate_document', models.FileField(upload_to='psychologists/certificates/')),
                ('total_session_minutes', models.PositiveIntegerField(default=0)),
                ('verified', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('specializations', models.ManyToManyField(blank=True, related_name='psychologists', to='psychologists.specialization')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='psychologist_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PsychologistExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255)),
                ('organization', models.CharField(max_length=255)),
                ('start_year', models.PositiveIntegerField()),
                ('end_year', models.PositiveIntegerField(blank=True, null=True)),
                ('currently_working', models.BooleanField(default=False)),
                ('psychologist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='psychologists.psychologistprofile')),
            ],
        ),
        migrations.CreateModel(
            name='PsychologistEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=255)),
                ('institution', models.CharField(max_length=255)),
                ('start_year', models.PositiveIntegerField()),
                ('end_year', models.PositiveIntegerField()),
                ('psychologist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='psychologists.psychologistprofile')),
            ],
        ),
    ]
