# Generated by Django 5.2.11 on 2026-03-07 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psychologists', '0002_psychologistprofile_psychologistexperience_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='psychologistexperience',
            name='psychologist',
        ),
        migrations.RemoveField(
            model_name='psychologistprofile',
            name='profile_picture',
        ),
        migrations.DeleteModel(
            name='PsychologistEducation',
        ),
        migrations.DeleteModel(
            name='PsychologistExperience',
        ),
    ]
