# Generated by Django 5.2.11 on 2026-03-25 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychologists', '0003_remove_psychologistexperience_psychologist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='psychologistprofile',
            name='highest_education',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
